<div id="formwrap">
<table cellspacing="0">
<tbody>
  <tr align="left" valign="center">
    <td class="title" colspan="2"><div class="titler" style="float:left;">Removing a HelpDesk operator</div><div style="float:right"><?= kvframework_markup::link_to_remote("cancel", array("update" => 'main_div', "url" => self::url_for('admin','index'), "loading" => 'doLoading(\'main\')')) ?></div></td>
  </tr>
  <tr>
    <td colspan="2" class="spacer"></td>
  </tr>
  <tr align="left" valign="top">
    <td colspan="2">Are you sure you want to remove this operator?</td>
  </tr>
  <tr>
    <td colspan="2" class="spacer"></td>
  </tr>
  <tr align="left" valign="top">
    <td colspan="2"><?= Helpdesker::select_name($this->thisguy) ?></td>
  </tr>
  <tr>
    <td colspan="2" class="spacer"></td>
  </tr>
  <tr align="left" valign="top">
    <td colspan="2">
    &raquo; <?= kvframework_markup::link_to_remote("Yes", array("update" => 'main_div', "url" => self::url_for('helpdesker_admin','process_delete_confirm', array("confirm" => 'yes', "hid" => $this->thisguy->helpdesker_id)), "loading" => 'doLoading(\'main\')')) ?><br />
    &raquo; <?= kvframework_markup::link_to_remote("No", array("update" => 'main_div', "url" => self::url_for('helpdesker_admin', 'process_delete_confirm', array("confirm" => 'no', "hid" => $this->thisguy->helpdesker_id)), "loading" => 'doLoading(\'main\')')) ?></td>
  </tr>
</tbody>
</table>
</div>