<?= $this->outputMessages1() ?>
<?= $this->outputErrors1() ?>

<div id="formwrap">
<?= kvframework_markup::form_remote_tag(array( "update" => 'main_div', "url" => self::url_for('system_admin', 'process_form'))) ?>
<table cellspacing="0">
<tbody>
  <tr align="left" valign="center">
    <td class="title" colspan="2"><div class="titler" style="float:left;">System Settings</div><div style="float:right"><?= kvframework_markup::link_to_remote( "cancel", array("update" => 'main_div', "url" => self::url_for('admin', 'index'), "loading" => 'doLoading(\'main\')')) ?></div></td>
  </tr>
  <?php uasort(CONFIG::$VARS, "callback_sysadmin_sort"); ?>
  <?php foreach(CONFIG::$VARS as $vkey => $varr){ ?>
  <tr>
    <td colspan="2" class="spacer"></td>
  </tr>
  <tr align="left" valign="top">
    <th><?= $varr[1] ?>:</th>
    <td><?= $this->output_option($vkey, $varr) ?></td>
  </tr>
  <?php } ?>
  <tr>
    <td colspan="2" class="spacer"></td>
  </tr>
  <tr align="left" valign="top">
    <th>&nbsp;</th>
    <td><input type="submit" value="save this data" class="txtbox3" /></td>
  </tr>
</tbody>
</table>
</form>
</div>