<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>KvScheduler</title>
<head>
  <link href="<?= CONFIG::rooturl ?>/css/fonts-min.css" media="screen" rel="Stylesheet" type="text/css" />
<link href="<?= CONFIG::rooturl ?>/css/default.css" media="screen" rel="Stylesheet" type="text/css" />
<script src="<?= CONFIG::rooturl ?>/javascripts/prototype.js" type="text/javascript"></script>
<script src="<?= CONFIG::rooturl ?>/javascripts/default.js" type="text/javascript"></script>
<script src="<?= CONFIG::rooturl ?>/javascripts/custom.js" type="text/javascript"></script>
<script src="<?= CONFIG::rooturl ?>/javascripts/moo.fx.js" type="text/javascript"></script>
<script src="<?= CONFIG::rooturl ?>/javascripts/moo.fx.pack.js" type="text/javascript"></script>
<script src="<?= CONFIG::rooturl ?>/javascripts/lightbox.js" type="text/javascript"></script>
</head>

<body>
  <div id="header">
  <div class="inner">
    <div id="topbar_div" class="menu-style" style="float:left;"></div>
    <div style="float:right;" class="menu-style"><a href="<?= CONFIG::rooturl ?>/"><span>Return to Home</span></a></div>
  </div>
  </div>
  <div id="logo"><img src="<?= CONFIG::rooturl ?>/images/logo.gif" width="763" height="21" alt="" /></div>
  <div id="container_div" class="clearfix">
    [CONTENT_FOR_LAYOUT]
  </div>
  <div id="footer"><img src="<?= CONFIG::rooturl ?>/images/footer.gif" width="763" height="2" alt="" /></div>
</body>
</html>
