<p><strong>RemoteCalendar Plug-In</strong><br />
<strong style='color: #ff0000;'>WARNING</strong>: This plug-in has broken some people's Outlook functionality. Try at your own risk. (It has also been seen to work fine on two computers in OEH)</p>

<p>
What you need (download and install in this order):
<ol>
<li>.NET Framework 2.0 - <a href="http://www.microsoft.com/downloads/details.aspx?FamilyID=0856EACB-4362-4B0D-8EDD-AAB15C5E04F5&displaylang=en" target="_new">download here</a><br />
<ul>Directions for Install: Run the installer</ul>
</li>
<li>RemoteCalendars 5.64 - <a href="https://sourceforge.net/project/showfiles.php?group_id=144247&package_id=158788&release_id=434657" target="_new">download here</a><br />
<ul>Directions for Install:<br>
<ol>
<li>Extract the Zip File</li>
<li>Extract(run) Prerequisites/O2003PIA.EXE to Prerequisites folder</li>
<li>Install Prerequisites/O2003PIA.msi</li>
<li>Install Prerequisites/vstor.exe</li>
<li>Install RemoteCalendars (run setup.exe)</li>
</ul>
</li>
</ol>
</p>
<p>
After that is all completed, you can start/restart Outlook and you should recieve a prompt to set basic options.  This is essentially self-explanatory. And you should see, on the Calendar screen in Outlook, a toolbar for RemoteCalendars.</p>
<p>
<strong>Importing your scheduler subscription</strong>
<ol>
<li>You should create a new calendar by right-clicking in the MyCalendars pane and selecting "New Folder...".  Name it whatever you like.</li>
<li>Click then "Subscribe to a remote calendar" button on the RemoteCalendars toolbar (green + icon).</li>
<li>Fill in the dialog with the URL from the iCal instructions page on the scheduler and name the calendar whatever you like.  Categories have not been tested, but work fine on default.  Select the outlook folder created above in the select box at the bottom and choose appropriate options for your use.</li>
<li>Click "OK" and the calendar should be added.</li>
</ol>
</p>

<p>
RemoteCalendars does not update the subscription automatically while Outlook is running as of this release.  If your options are set to Automatic Update, it will update when Outlook starts, but not after that. This means you need to mamnually update the subscriptions by clicking the refresh button on the RemoteCalendars toolbar (two arrows in a circle icon).
</p>

<p>
The features described here are the only features that have been remotely tested for use with the scheduler. Again, use this plug-in and its features at your own risk.
</p>
