<?= $this->outputMessages1() ?>
<?= $this->outputErrors1() ?>
<div id="formwrap">
<form method="post" action="<?= self::url_for('user', "login_form_process") ?>">
<table cellspacing="0">
<tbody>
  <tr align="left" valign="center">
    <td class="title" colspan="2"><div class="titler" style="float:left;">Logging in</div></td>
  </tr>
  <tr>
    <td colspan="2" class="spacer"></td>
  </tr>
  <tr align="left" valign="top">
    <th>Username:</th>
    <td><input type="text" name="username" id="username" class="txtbox1" /></td>
  </tr>
  <tr>
    <td colspan="2" class="spacer"></td>
  </tr>
  <tr align="left" valign="top">
    <th>Password:</th>
    <td><input type="password" name="password" id="password" class="txtbox1" /></td>
  </tr>
  <tr>
    <td colspan="2" class="spacer"></td>
  </tr>
  <tr align="left" valign="top">
    <th>&nbsp;</th>
    <td><input type="submit" value="Log In" class="txtbox3" /></td>
  </tr>
</tbody>
</table>
</form>
</div>