<div id="formwrap">
<table cellspacing="0">
<tbody>
  <tr align="left" valign="center">
    <td class="title"><div class="titler" style="float:left;">You have successfully logged out</div></td>
  </tr>
  <tr>
    <td colspan="2" class="spacer"></td>
  </tr>
  <tr align="left" valign="top">
    <th>&raquo;
    <a href="<?= self::url_for("user", "login_form") ?>">log in again</a>
    </th>
  </tr>
</tbody>
</table>
</div>