<?= $this->outputErrors1() ?>
<?= $this->outputMessages1() ?>

<div id="formwrap">
<?= kvframework_markup::form_remote_tag(array("update" => 'main_div', "url" => self::url_for('calendar', 'process_ticket'), "loading" => "doLoading('main');")) ?>
<table cellspacing="0">
<tbody>
  <tr align="left" valign="center">
    <td class="title" colspan="2"><div class="titler" style="float:left;">Reports: Remedy Ticket</div><div style="float:right"><?= kvframework_markup::link_to_remote("cancel", array("update" => 'main_div', "url" => self::url_for('calendar', 'display_date_full'), "loading" => 'doLoading(\'main\')', "complete" => "windowload();")) ?></div></td>
  </tr>
  <tr>
    <td colspan="2" class="spacer"></td>
  </tr>
  <tr align="left" valign="top">
    <th>Ticket Number List:</th>
    <td><input type="text" name="ticket" id="ticket" value="<?= (array_key_exists("ticket", self::$PARAMS)) ? self::$PARAMS["ticket"] : "" ?>" class="txtbox1" /></td>
  </tr>
  <tr>
    <td colspan="2" class="spacer"></td>
  </tr>
  <tr align="left" valign="top">
    <th>&nbsp;</th>
    <td><input type="submit" value="Generate" class="txtbox3" /></td>
  </tr>
</tbody>
</table>
</form>
</div>
