CREATE TABLE IF NOT EXISTS appointments(
  id BIGINT unsigned not null auto_increment,
  PRIMARY KEY(id),
  starttime TIME not null,
  stoptime TIME not null,
  startdate DATE not null,
  stopdate DATE not null,
  location_id MEDIUMINT unsigned not null,
  locdetails VARCHAR(255) not null,
  special ENUM('regular','repeat_removal') not null default 'regular',
  removal_of BIGINT unsigned not null,
  special2 ENUM('regular','meeting','meecket') not null default 'regular',
  repeat ENUM('TRUE','FALSE') not null default 'FALSE',
  repetition_day SET('M','T','W','H','F','S','N') not null default '',
  repetition_week TINYINT unsigned not null,
  lockout ENUM('TRUE','FALSE') not null default 'FALSE',
  lockout_user VARCHAR(255) not null,
  appointment_user VARCHAR(255) not null,
  timestamp INT unsigned not null,
  ical_sequence INT unsigned not null default 0,
  tm_id BIGINT unsigned not null,
  tm_type VARCHAR(255) not null,
  KEY(lockout),
  KEY(location_id),
  KEY(tm_id, tm_type)
) Type=InnoDB;
